{
  "story_id": "emilia-noqa-20250828-033143",
  "source": "local",
  "created_at": "2025-08-28T03:31:43.885061",
  "updated_at": "2025-08-28T03:32:09.991932",
  "estado": "error",
  "paso_actual": "cuentacuentos",
  "qa_historial": {
    "director": {
      "arco_completo": 5,
      "claridad_visual": 5,
      "potencia_leitmotiv": 5,
      "promedio": 5.0
    },
    "psicoeducador": {
      "ajuste_edad": 5,
      "alineacion_mensaje": 5,
      "tono_amable": 5,
      "promedio": 5.0
    }
  },
  "devoluciones": [],
  "reintentos": {},
  "timestamps": {
    "director": {
      "start": "2025-08-28T03:31:43.886434",
      "end": "2025-08-28T03:31:55.091625",
      "duration": 11.205188
    },
    "psicoeducador": {
      "start": "2025-08-28T03:31:55.092288",
      "end": "2025-08-28T03:32:09.991676",
      "duration": 14.899385
    },
    "cuentacuentos": {
      "start": "2025-08-28T03:32:09.992285",
      "end": "2025-08-28T03:33:46.960254",
      "duration": 96.96796
    }
  },
  "webhook_url": null,
  "webhook_attempts": 0,
  "configuracion_modelo": {
    "modelo": "openai/gpt-oss-120b",
    "endpoint": "http://69.19.136.204:8000/v1/chat/completions",
    "timeout": 900,
    "default_temperature": 0.7,
    "default_max_tokens": 4000
  },
  "error": {
    "agent": "cuentacuentos",
    "message": "Fallo después de 3 intentos. Último error: Error en intento 3: El modelo no generó contenido",
    "timestamp": "2025-08-28T03:33:46.960282"
  }
}